# Generated by Django 5.2.17 on 2026-09-24 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_referencia", models.CharField(blank=True, max_length=100)),
                ("titulo", models.CharField(max_length=500)),
                ("fechas", models.CharField(blank=True, max_length=100)),
                (
                    "nivel_descripcion",
                    models.CharField(
                        choices=[
                            ("fondo", "Fondo"),
                            ("seccion", "Sección"),
                            ("serie", "Serie"),
                            ("unidad", "Unidad documental"),
                        ],
                        default="unidad",
                        max_length=10,
                    ),
                ),
                ("volumen_soporte", models.CharField(blank=True, max_length=255)),
                ("productor", models.CharField(blank=True, max_length=255)),
                ("alcance_contenido", models.TextField(blank=True)),
                ("archivo", models.FileField(upload_to="acervo/%Y/%m/")),
                ("sha256", models.CharField(editable=False, max_length=64)),
                (
                    "formato",
                    models.CharField(blank=True, editable=False, max_length=100),
                ),
                ("tamano_bytes", models.BigIntegerField(default=0, editable=False)),
                ("texto_extraido", models.TextField(blank=True)),
                ("fecha_ingreso", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventoPreservacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ingreso", "Ingreso"),
                            ("verificacion_fijeza", "Verificación de fijeza"),
                            ("sugerencia_ia", "Sugerencia generada por IA"),
                            ("validacion_humana", "Validación humana"),
                            ("modificacion_metadatos", "Modificación de metadatos"),
                        ],
                        max_length=30,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("agente", models.CharField(max_length=255)),
                ("detalle", models.JSONField(default=dict)),
                ("exitoso", models.BooleanField(default=True)),
                ("hash_anterior", models.CharField(editable=False, max_length=64)),
                ("hash_evento", models.CharField(editable=False, max_length=64)),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos",
                        to="acervo.documento",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
