# Generated by Django 5.2.17 on 2026-09-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acervo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventopreservacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ingreso", "Ingreso"),
                    ("verificacion_fijeza", "Verificación de fijeza"),
                    ("extraccion_texto", "Extracción de texto (OCR)"),
                    ("sugerencia_ia", "Sugerencia generada por IA"),
                    ("validacion_humana", "Validación humana"),
                    ("modificacion_metadatos", "Modificación de metadatos"),
                ],
                max_length=30,
            ),
        ),
    ]
