# Generated by Django 5.2.17 on 2026-09-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acervo", "0002_evento_extraccion"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="publicado",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="documento",
            name="texto_publico",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="Texto que se muestra al público, con los datos personales ocultos si se decidió anonimizar.",
            ),
        ),
        migrations.AlterField(
            model_name="eventopreservacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ingreso", "Ingreso"),
                    ("verificacion_fijeza", "Verificación de fijeza"),
                    ("extraccion_texto", "Extracción de texto (OCR)"),
                    ("sugerencia_ia", "Sugerencia generada por IA"),
                    ("validacion_humana", "Validación humana"),
                    ("modificacion_metadatos", "Modificación de metadatos"),
                    ("revision_datos_personales", "Revisión de datos personales"),
                    ("aprobacion_publicacion", "Aprobación de publicación"),
                ],
                max_length=30,
            ),
        ),
    ]
