# Generated by Django 5.2.17 on 2026-09-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acervo", "0003_documento_publicado_documento_texto_publico_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("persona", "Persona"),
                            ("lugar", "Lugar"),
                            ("institucion", "Institución"),
                        ],
                        max_length=12,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "documentos",
                    models.ManyToManyField(
                        blank=True, related_name="entidades", to="acervo.documento"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "entidades",
                "ordering": ["tipo", "nombre"],
                "unique_together": {("tipo", "nombre")},
            },
        ),
    ]
