# Generated by Django 5.2.17 on 2026-09-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acervo", "0004_entidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadClasificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("fondo", "Fondo"),
                            ("seccion", "Sección"),
                            ("serie", "Serie"),
                            ("subserie", "Subserie"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Qué tipo de documentos agrupa; es lo que la IA compara contra el texto.",
                    ),
                ),
                (
                    "palabras_clave",
                    models.CharField(
                        blank=True,
                        help_text="Términos separados por comas, usados por el proveedor de IA local para proponer coincidencias.",
                        max_length=500,
                    ),
                ),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hijos",
                        to="acervo.unidadclasificacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "unidad del cuadro de clasificación",
                "verbose_name_plural": "cuadro de clasificación",
                "ordering": ["codigo"],
            },
        ),
        migrations.AddField(
            model_name="documento",
            name="unidad_clasificacion",
            field=models.ForeignKey(
                blank=True,
                help_text="Serie o subserie del cuadro de clasificación.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos",
                to="acervo.unidadclasificacion",
            ),
        ),
    ]
