# Generated by Django 5.2.17 on 2026-09-25 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acervo", "0005_unidadclasificacion_documento_unidad_clasificacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventopreservacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ingreso", "Ingreso"),
                    ("verificacion_fijeza", "Verificación de fijeza"),
                    ("extraccion_texto", "Extracción de texto (OCR)"),
                    ("sugerencia_ia", "Sugerencia generada por IA"),
                    ("validacion_humana", "Validación humana"),
                    ("modificacion_metadatos", "Modificación de metadatos"),
                    ("revision_datos_personales", "Revisión de datos personales"),
                    ("aprobacion_publicacion", "Aprobación de publicación"),
                    ("exportacion_metadatos", "Exportación de metadatos"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="RelacionEntidadDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_relacion",
                    models.CharField(
                        choices=[
                            ("productor", "Productor"),
                            ("mencionado", "Mencionado"),
                            ("destinatario", "Destinatario"),
                        ],
                        default="mencionado",
                        max_length=15,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acervo.documento",
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acervo.entidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "relación entidad–documento",
                "verbose_name_plural": "relaciones entidad–documento",
                "unique_together": {("documento", "entidad", "tipo_relacion")},
            },
        ),
        migrations.RemoveField(
            model_name="entidad",
            name="documentos",
        ),
        migrations.AddField(
            model_name="entidad",
            name="documentos",
            field=models.ManyToManyField(
                blank=True,
                related_name="entidades",
                through="acervo.RelacionEntidadDocumento",
                to="acervo.documento",
            ),
        ),
    ]
