# Generated by Django 5.2.17 on 2026-09-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acervo", "0006_alter_eventopreservacion_tipo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entidad",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("persona", "Persona"),
                    ("lugar", "Lugar"),
                    ("institucion", "Institución"),
                    ("actividad", "Actividad"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="relacionentidaddocumento",
            name="tipo_relacion",
            field=models.CharField(
                choices=[
                    ("productor", "Productor"),
                    ("mencionado", "Mencionado"),
                    ("destinatario", "Destinatario"),
                    ("documenta", "Documenta (actividad testimoniada)"),
                    ("trata_sobre", "Trata sobre"),
                    ("lugar_produccion", "Lugar de producción"),
                ],
                default="mencionado",
                max_length=20,
            ),
        ),
    ]
