# Generated by Django 5.2.17 on 2026-09-26 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acervo", "0007_alter_entidad_tipo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelacionEntidadUnidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_relacion",
                    models.CharField(
                        choices=[("productor", "Productor")],
                        default="productor",
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acervo.entidad"
                    ),
                ),
                (
                    "unidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relaciones_entidad",
                        to="acervo.unidadclasificacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "relación entidad–unidad de clasificación",
                "verbose_name_plural": "relaciones entidad–unidad de clasificación",
                "unique_together": {("unidad", "entidad", "tipo_relacion")},
            },
        ),
    ]
