# Generated by Django 5.2.17 on 2026-09-24 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("acervo", "0001_initial"),
        ("lineamientos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SugerenciaIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proceso",
                    models.CharField(
                        choices=[
                            ("clasificacion", "Clasificación"),
                            ("descripcion", "Descripción"),
                            ("valoracion", "Valoración"),
                            ("metadatos", "Gestión de metadatos"),
                            ("acceso", "Acceso"),
                        ],
                        max_length=20,
                    ),
                ),
                ("campo", models.CharField(max_length=50)),
                ("valor_propuesto", models.TextField()),
                ("justificacion", models.TextField(blank=True)),
                (
                    "confianza",
                    models.FloatField(
                        help_text="Entre 0 y 1, según el proveedor de IA."
                    ),
                ),
                ("modelo", models.CharField(max_length=100)),
                ("version_modelo", models.CharField(max_length=50)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de validación"),
                            ("aceptada", "Aceptada"),
                            ("modificada", "Aceptada con cambios"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=12,
                    ),
                ),
                ("valor_final", models.TextField(blank=True)),
                ("motivo_decision", models.TextField(blank=True)),
                ("fecha_validacion", models.DateTimeField(blank=True, null=True)),
                (
                    "criterios",
                    models.ManyToManyField(blank=True, to="lineamientos.criterio"),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sugerencias",
                        to="acervo.documento",
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "sugerencia de IA",
                "verbose_name_plural": "sugerencias de IA",
                "ordering": ["-fecha"],
            },
        ),
    ]
