# Generated by Django 5.2.17 on 2026-09-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sugerenciaia",
            name="evidencia",
            field=models.TextField(
                blank=True,
                help_text="Fragmento literal del documento que respalda la propuesta.",
            ),
        ),
        migrations.AddField(
            model_name="sugerenciaia",
            name="evidencia_verificada",
            field=models.BooleanField(
                help_text="Si MAZUCA encontró la evidencia en el texto del documento.",
                null=True,
            ),
        ),
    ]
