# Generated by Django 5.2.17 on 2026-09-25 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencia", "0002_sugerenciaia_evidencia_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sugerenciaia",
            name="relacion",
            field=models.CharField(
                blank=True,
                help_text="Solo para entidades (DES-04): tipo de relación con el documento (productor, mencionado, destinatario), al estilo Records in Context.",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="MuestraAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_seleccion", models.DateTimeField(auto_now_add=True)),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de revisión"),
                            ("correcta", "La IA acertó"),
                            ("incorrecta", "La IA se equivocó"),
                        ],
                        default="pendiente",
                        max_length=12,
                    ),
                ),
                ("observacion", models.TextField(blank=True)),
                ("fecha_revision", models.DateTimeField(blank=True, null=True)),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sugerencia",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="asistencia.sugerenciaia",
                    ),
                ),
            ],
            options={
                "verbose_name": "muestra de auditoría",
                "verbose_name_plural": "muestras de auditoría",
                "ordering": ["-fecha_seleccion"],
            },
        ),
    ]
