# Generated by Django 5.2.17 on 2026-09-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencia", "0003_sugerenciaia_relacion_muestraauditoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sugerenciaia",
            name="relacion",
            field=models.CharField(
                blank=True,
                help_text="Solo para entidades (DES-04): tipo de relación con el documento (productor, mencionado, destinatario, documenta, trata_sobre, lugar_produccion), al estilo Records in Context.",
                max_length=20,
            ),
        ),
    ]
