# Generated by Django 5.2.17 on 2026-09-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencia", "0004_alter_sugerenciaia_relacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="sugerenciaia",
            name="entidad_nombre",
            field=models.CharField(
                blank=True,
                help_text="Solo para valoración: nombre de esa entidad.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sugerenciaia",
            name="entidad_tipo",
            field=models.CharField(
                blank=True,
                help_text="Solo para valoración: tipo de la entidad del grafo RiC que justifica el indicio (persona, institucion, lugar o actividad), si se identificó una.",
                max_length=12,
            ),
        ),
    ]
