# Generated by Django 5.2.17 on 2026-09-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencia", "0005_sugerenciaia_entidad_nombre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sugerenciaia",
            name="evidencia_verificada",
            field=models.BooleanField(
                help_text="Si RICORA encontró la evidencia en el texto del documento.",
                null=True,
            ),
        ),
    ]
