# Generated by Django 5.2.17 on 2026-09-26 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificador",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A22 Identifier: identifica la entidad dentro de un dominio dado.",
                        max_length=255,
                    ),
                ),
                ("nombre", models.CharField(help_text="RiC-A28 Name.", max_length=500)),
                (
                    "descripcion_general",
                    models.TextField(
                        blank=True, help_text="RiC-A43 General Description."
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "tipo_evento",
                    models.CharField(
                        blank=True, help_text="RiC-A18 Event Type.", max_length=255
                    ),
                ),
                (
                    "historia",
                    models.TextField(blank=True, help_text="RiC-A21 History."),
                ),
            ],
            options={
                "verbose_name": "evento",
                "verbose_name_plural": "eventos",
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificador",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A22 Identifier: identifica la entidad dentro de un dominio dado.",
                        max_length=255,
                    ),
                ),
                ("nombre", models.CharField(help_text="RiC-A28 Name.", max_length=500)),
                (
                    "descripcion_general",
                    models.TextField(
                        blank=True, help_text="RiC-A43 General Description."
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "historia",
                    models.TextField(blank=True, help_text="RiC-A21 History."),
                ),
                (
                    "idioma",
                    models.CharField(
                        blank=True, help_text="RiC-A25 Language.", max_length=255
                    ),
                ),
                (
                    "estatus_legal",
                    models.CharField(
                        blank=True, help_text="RiC-A26 Legal Status.", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "agente",
                "verbose_name_plural": "agentes",
            },
        ),
        migrations.CreateModel(
            name="Date",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificador",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A22 Identifier: identifica la entidad dentro de un dominio dado.",
                        max_length=255,
                    ),
                ),
                ("nombre", models.CharField(help_text="RiC-A28 Name.", max_length=500)),
                (
                    "descripcion_general",
                    models.TextField(
                        blank=True, help_text="RiC-A43 General Description."
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "expresion",
                    models.CharField(
                        blank=True, help_text="RiC-A19 Expressed Date.", max_length=255
                    ),
                ),
                (
                    "valor_normalizado",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A29 Normalized Date (ISO 8601 / EDTF).",
                        max_length=100,
                    ),
                ),
                (
                    "calificador",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A13 Date Qualifier. La certeza de la fecha frente a OTRA entidad va en la RelacionRiC que las conecta (RiC-RA01), no aquí.",
                        max_length=50,
                    ),
                ),
                (
                    "tipo_fecha",
                    models.CharField(
                        blank=True, help_text="RiC-A42 Date Type.", max_length=100
                    ),
                ),
            ],
            options={
                "verbose_name": "fecha",
                "verbose_name_plural": "fechas",
            },
        ),
        migrations.CreateModel(
            name="Instantiation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificador",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A22 Identifier: identifica la entidad dentro de un dominio dado.",
                        max_length=255,
                    ),
                ),
                ("nombre", models.CharField(help_text="RiC-A28 Name.", max_length=500)),
                (
                    "descripcion_general",
                    models.TextField(
                        blank=True, help_text="RiC-A43 General Description."
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("archivo", models.FileField(upload_to="ric/instanciaciones/%Y/%m/")),
                (
                    "sha256",
                    models.CharField(
                        editable=False,
                        help_text="No es un atributo de RiC-CM: extensión de preservación digital (RiC-CM 1.0, sección 1.9).",
                        max_length=64,
                    ),
                ),
                (
                    "tipo_soporte",
                    models.CharField(
                        blank=True, help_text="RiC-A05 Carrier Type.", max_length=255
                    ),
                ),
                (
                    "extension_soporte",
                    models.CharField(
                        blank=True, help_text="RiC-A04 Carrier Extent.", max_length=255
                    ),
                ),
                (
                    "tipo_representacion",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A37 Representation Type.",
                        max_length=255,
                    ),
                ),
                (
                    "caracteristicas_fisicas",
                    models.TextField(
                        blank=True, help_text="RiC-A31 Physical Characteristics Note."
                    ),
                ),
            ],
            options={
                "verbose_name": "instanciación (Instantiation)",
                "verbose_name_plural": "instanciaciones (Instantiation)",
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificador",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A22 Identifier: identifica la entidad dentro de un dominio dado.",
                        max_length=255,
                    ),
                ),
                ("nombre", models.CharField(help_text="RiC-A28 Name.", max_length=500)),
                (
                    "descripcion_general",
                    models.TextField(
                        blank=True, help_text="RiC-A43 General Description."
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "tipo_regla",
                    models.CharField(
                        blank=True, help_text="RiC-A45 Rule Type.", max_length=255
                    ),
                ),
                (
                    "historia",
                    models.TextField(blank=True, help_text="RiC-A21 History."),
                ),
            ],
            options={
                "verbose_name": "regla",
                "verbose_name_plural": "reglas",
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificador",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A22 Identifier: identifica la entidad dentro de un dominio dado.",
                        max_length=255,
                    ),
                ),
                ("nombre", models.CharField(help_text="RiC-A28 Name.", max_length=500)),
                (
                    "descripcion_general",
                    models.TextField(
                        blank=True, help_text="RiC-A43 General Description."
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "coordenadas",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A11 Coordinates (ISO 6709).",
                        max_length=255,
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, help_text="RiC-A27 Location.", max_length=500
                    ),
                ),
                (
                    "tipo_lugar",
                    models.CharField(
                        blank=True, help_text="RiC-A32 Place Type.", max_length=255
                    ),
                ),
                (
                    "historia",
                    models.TextField(blank=True, help_text="RiC-A21 History."),
                ),
            ],
            options={
                "verbose_name": "lugar",
                "verbose_name_plural": "lugares",
            },
        ),
        migrations.CreateModel(
            name="RecordResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificador",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A22 Identifier: identifica la entidad dentro de un dominio dado.",
                        max_length=255,
                    ),
                ),
                ("nombre", models.CharField(help_text="RiC-A28 Name.", max_length=500)),
                (
                    "descripcion_general",
                    models.TextField(
                        blank=True, help_text="RiC-A43 General Description."
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "autenticidad",
                    models.TextField(
                        blank=True, help_text="RiC-A03 Authenticity Note."
                    ),
                ),
                (
                    "clasificacion",
                    models.CharField(
                        blank=True, help_text="RiC-A07 Classification.", max_length=255
                    ),
                ),
                (
                    "condiciones_acceso",
                    models.TextField(
                        blank=True, help_text="RiC-A08 Conditions of Access."
                    ),
                ),
                (
                    "condiciones_uso",
                    models.TextField(
                        blank=True, help_text="RiC-A09 Conditions of Use."
                    ),
                ),
                (
                    "tipo_contenido",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A10 Content Type (simplificado a texto libre; RiC-O lo trata como clase controlada).",
                        max_length=255,
                    ),
                ),
                (
                    "historia",
                    models.TextField(blank=True, help_text="RiC-A21 History."),
                ),
                (
                    "nota_integridad",
                    models.TextField(blank=True, help_text="RiC-A24 Integrity Note."),
                ),
                (
                    "idioma",
                    models.CharField(
                        blank=True, help_text="RiC-A25 Language.", max_length=255
                    ),
                ),
                (
                    "estatus_legal",
                    models.CharField(
                        blank=True, help_text="RiC-A26 Legal Status.", max_length=255
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A35 Record Resource Extent.",
                        max_length=255,
                    ),
                ),
                (
                    "alcance_y_contenido",
                    models.TextField(
                        blank=True, help_text="RiC-A38 Scope and content."
                    ),
                ),
                (
                    "estado_produccion",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A39 State (RiC-O: 'Record State'). Solo aplica a Record/Record Part.",
                        max_length=50,
                    ),
                ),
                (
                    "estructura",
                    models.TextField(blank=True, help_text="RiC-A40 Structure."),
                ),
            ],
            options={
                "verbose_name": "recurso documental",
                "verbose_name_plural": "recursos documentales",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ric.event",
                    ),
                ),
                (
                    "tipo_actividad",
                    models.CharField(
                        blank=True, help_text="RiC-A02 Activity Type.", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "actividad",
                "verbose_name_plural": "actividades",
            },
            bases=("ric.event",),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "agent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ric.agent",
                    ),
                ),
                (
                    "grupo_demografico",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A15 Demographic Group.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "grupo",
                "verbose_name_plural": "grupos",
            },
            bases=("ric.agent",),
        ),
        migrations.CreateModel(
            name="Mechanism",
            fields=[
                (
                    "agent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ric.agent",
                    ),
                ),
                (
                    "caracteristicas_tecnicas",
                    models.TextField(
                        blank=True, help_text="RiC-A41 Technical Characteristics."
                    ),
                ),
            ],
            options={
                "verbose_name": "mecanismo",
                "verbose_name_plural": "mecanismos",
            },
            bases=("ric.agent",),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "agent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ric.agent",
                    ),
                ),
                (
                    "tipo_ocupacion",
                    models.CharField(
                        blank=True, help_text="RiC-A30 Occupation Type.", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "persona",
                "verbose_name_plural": "personas",
            },
            bases=("ric.agent",),
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "agent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ric.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "posición (cargo)",
                "verbose_name_plural": "posiciones (cargos)",
            },
            bases=("ric.agent",),
        ),
        migrations.CreateModel(
            name="Evidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pagina", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fragmento",
                    models.TextField(help_text="Texto literal citado como evidencia."),
                ),
                (
                    "posicion",
                    models.JSONField(
                        blank=True,
                        help_text="Coordenadas (bbox) cuando el proveedor de IA las entrega.",
                        null=True,
                    ),
                ),
                (
                    "verificada",
                    models.BooleanField(
                        help_text="Si el fragmento se encontró literalmente en el texto extraído de la instanciación.",
                        null=True,
                    ),
                ),
                (
                    "instanciacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="ric.instantiation",
                    ),
                ),
            ],
            options={
                "verbose_name": "evidencia",
                "verbose_name_plural": "evidencias",
            },
        ),
        migrations.CreateModel(
            name="Mandate",
            fields=[
                (
                    "rule_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ric.rule",
                    ),
                ),
                (
                    "tipo_mandato",
                    models.CharField(
                        blank=True, help_text="RiC-A44 Mandate Type.", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "mandato",
                "verbose_name_plural": "mandatos",
            },
            bases=("ric.rule",),
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "recordresource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ric.recordresource",
                    ),
                ),
                (
                    "tipo_forma_documental",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A17 Documentary Form Type.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "registro (Record)",
                "verbose_name_plural": "registros (Record)",
            },
            bases=("ric.recordresource",),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="record_resource",
            field=models.ForeignKey(
                help_text="RiC-R025 'has or had instantiation'.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instanciaciones",
                to="ric.recordresource",
            ),
        ),
        migrations.CreateModel(
            name="RelacionRiC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relacion_id",
                    models.CharField(
                        help_text="Ej. 'R026'. Ver ric/fixtures/ric_matrix.json.",
                        max_length=10,
                    ),
                ),
                ("origen_object_id", models.PositiveBigIntegerField()),
                ("destino_object_id", models.PositiveBigIntegerField()),
                (
                    "certeza",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("certain", "Cierta"),
                            ("uncertain", "Incierta"),
                            ("unknown", "Desconocida"),
                        ],
                        help_text="RiC-RA01.",
                        max_length=12,
                    ),
                ),
                (
                    "descripcion_relacion",
                    models.TextField(
                        blank=True, help_text="RiC-RA03 Description of Relation."
                    ),
                ),
                (
                    "fuente_relacion",
                    models.TextField(
                        blank=True, help_text="RiC-RA05 Source of Relation."
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de validación"),
                            ("aceptada", "Aceptada"),
                            ("modificada", "Aceptada con cambios"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=12,
                    ),
                ),
                ("fecha_validacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "destino_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "evidencia",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nula si la relación se creó a mano por el archivista, sin propuesta de IA de por medio.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relaciones",
                        to="ric.evidencia",
                    ),
                ),
                (
                    "origen_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relaciones_validadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "relación RiC",
                "verbose_name_plural": "relaciones RiC",
            },
        ),
        migrations.CreateModel(
            name="CorporateBody",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ric.group",
                    ),
                ),
                (
                    "tipo_entidad_corporativa",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A12 Corporate Body Type.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "entidad corporativa",
                "verbose_name_plural": "entidades corporativas",
            },
            bases=("ric.group",),
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ric.group",
                    ),
                ),
                (
                    "tipo_familia",
                    models.CharField(
                        blank=True, help_text="RiC-A20 Family Type.", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "familia",
                "verbose_name_plural": "familias",
            },
            bases=("ric.group",),
        ),
        migrations.CreateModel(
            name="RecordPart",
            fields=[
                (
                    "recordresource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ric.recordresource",
                    ),
                ),
                (
                    "tipo_forma_documental",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A17 Documentary Form Type.",
                        max_length=255,
                    ),
                ),
                (
                    "record_padre",
                    models.ForeignKey(
                        help_text="RiC-R003 'has or had constituent' (caso Record -> Record Part).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partes",
                        to="ric.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "parte de registro (Record Part)",
                "verbose_name_plural": "partes de registro (Record Part)",
            },
            bases=("ric.recordresource",),
        ),
        migrations.CreateModel(
            name="RecordSet",
            fields=[
                (
                    "recordresource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ric.recordresource",
                    ),
                ),
                (
                    "accruals",
                    models.CharField(
                        blank=True, help_text="RiC-A01 Accruals.", max_length=255
                    ),
                ),
                (
                    "tipo_conjunto",
                    models.CharField(
                        blank=True,
                        help_text="RiC-A36 Record Set Type: fondo, sección, serie, subserie, colección...",
                        max_length=50,
                    ),
                ),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        help_text="Caso común de RiC-R024 'includes or included' entre Record Sets; el caso general se modela con RelacionRiC.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hijos",
                        to="ric.recordset",
                    ),
                ),
            ],
            options={
                "verbose_name": "conjunto de registros (Record Set)",
                "verbose_name_plural": "conjuntos de registros (Record Set)",
            },
            bases=("ric.recordresource",),
        ),
        migrations.AddField(
            model_name="record",
            name="record_set",
            field=models.ForeignKey(
                blank=True,
                help_text="Caso común de RiC-R024 'includes or included'; el caso general se modela con RelacionRiC.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="ric.recordset",
            ),
        ),
    ]
