# Generated by Django 5.2.17 on 2026-09-26 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaginaTexto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("texto", models.TextField(blank=True)),
                ("uso_ocr", models.BooleanField(default=False)),
                ("confianza_ocr", models.FloatField(blank=True, null=True)),
                (
                    "instanciacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paginas",
                        to="ric.instantiation",
                    ),
                ),
            ],
            options={
                "verbose_name": "página de texto",
                "verbose_name_plural": "páginas de texto",
                "ordering": ["numero"],
                "unique_together": {("instanciacion", "numero")},
            },
        ),
    ]
