# Generated by Django 5.2.17 on 2026-09-26 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ric", "0002_paginatexto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropuestaRiC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origen_object_id", models.PositiveBigIntegerField()),
                (
                    "relacion_id",
                    models.CharField(help_text="Ej. 'R027'.", max_length=10),
                ),
                (
                    "entidad_tipo",
                    models.CharField(
                        help_text="Ej. 'E11'. Tipo de la entidad destino propuesta.",
                        max_length=10,
                    ),
                ),
                ("entidad_nombre", models.CharField(max_length=500)),
                (
                    "proveedor",
                    models.CharField(
                        help_text="Nombre del ProveedorIA que la generó.", max_length=50
                    ),
                ),
                ("version_modelo", models.CharField(blank=True, max_length=100)),
                ("confianza", models.FloatField(help_text="Entre 0 y 1.")),
                ("justificacion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de validación"),
                            ("aceptada", "Aceptada"),
                            ("modificada", "Aceptada con cambios"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=12,
                    ),
                ),
                (
                    "motivo_decision",
                    models.TextField(
                        blank=True,
                        help_text="Por qué se rechazó: del motor de reglas (automático) o de la persona archivista.",
                    ),
                ),
                ("fecha_validacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "evidencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propuestas",
                        to="ric.evidencia",
                    ),
                ),
                (
                    "origen_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="propuestas_ric_validadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "propuesta de IA (RiC)",
                "verbose_name_plural": "propuestas de IA (RiC)",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
