# Generated by Django 5.2.17 on 2026-09-26 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0003_propuestaric"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoRiC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("extraccion_texto", "Extracción de texto (OCR)"),
                            ("propuesta_ia", "Propuesta generada por IA"),
                            ("validacion_humana", "Validación humana"),
                        ],
                        max_length=30,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("agente", models.CharField(max_length=255)),
                ("detalle", models.JSONField(default=dict)),
                ("exitoso", models.BooleanField(default=True)),
                ("hash_anterior", models.CharField(editable=False, max_length=64)),
                ("hash_evento", models.CharField(editable=False, max_length=64)),
                (
                    "instanciacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos",
                        to="ric.instantiation",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento (bitácora RiC)",
                "verbose_name_plural": "eventos (bitácora RiC)",
                "ordering": ["id"],
            },
        ),
    ]
