# Generated by Django 5.2.17 on 2026-09-26 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0005_pg_trgm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MuestraRiC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_seleccion", models.DateTimeField(auto_now_add=True)),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de revisión"),
                            ("correcta", "La IA acertó"),
                            ("incorrecta", "La IA se equivocó"),
                        ],
                        default="pendiente",
                        max_length=12,
                    ),
                ),
                ("observacion", models.TextField(blank=True)),
                ("fecha_revision", models.DateTimeField(blank=True, null=True)),
                (
                    "relacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muestra_auditoria",
                        to="ric.relacionric",
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "muestra de auditoría RiC",
                "verbose_name_plural": "muestras de auditoría RiC",
                "ordering": ["-fecha_seleccion"],
            },
        ),
    ]
