# Generated by Django 5.2.17 on 2026-09-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0006_muestraric"),
    ]

    operations = [
        migrations.AddField(
            model_name="paginatexto",
            name="cajas_ocr",
            field=models.JSONField(
                blank=True,
                help_text="F02: caja delimitadora de cada palabra reconocida por OCR (izquierda/arriba/ancho/alto en píxeles, más su confianza). Vacío cuando la página no tuvo OCR (texto plano o capa de texto de PDF).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evidencia",
            name="posicion",
            field=models.JSONField(
                blank=True,
                help_text="F02: caja delimitadora (bbox) del fragmento sobre la página OCR, calculada automáticamente cuando la página tiene coordenadas de OCR (ver ric.evidencia.localizar_posicion); vacía si la página no tuvo OCR.",
                null=True,
            ),
        ),
    ]
