# Generated by Django 5.2.17 on 2026-09-27 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0007_paginatexto_cajas_ocr_alter_evidencia_posicion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponenteEstructural",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pagina", models.PositiveIntegerField()),
                (
                    "orden",
                    models.PositiveIntegerField(
                        help_text="Posición del componente dentro de la página, en orden de lectura."
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("encabezado", "Encabezado institucional"),
                            ("titulo", "Título / identificador del documento"),
                            ("campo", "Campo (PARA/DE/ASUNTO/FECHA/LUGAR...)"),
                            ("fecha", "Fecha"),
                            ("seccion", "Encabezado de sección"),
                            ("articulo", "Artículo"),
                            ("parrafo", "Párrafo"),
                            ("firma", "Firma"),
                            ("tabla", "Tabla"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "etiqueta",
                    models.CharField(
                        blank=True,
                        help_text="Para tipo=campo: PARA, DE, ASUNTO...; para tipo=articulo: 'ARTÍCULO 1'.",
                        max_length=50,
                    ),
                ),
                ("texto", models.TextField(blank=True)),
                (
                    "datos",
                    models.JSONField(
                        blank=True,
                        help_text="Para tipo=tabla: filas/columnas; para tipo=fecha: el texto de la fecha reconocida.",
                        null=True,
                    ),
                ),
                (
                    "confianza",
                    models.FloatField(
                        help_text="Heurística basada en reglas: más alta cuanto más específica la regla, más baja si es por descarte."
                    ),
                ),
                (
                    "regla",
                    models.CharField(
                        help_text="Nombre de la regla que detectó este componente.",
                        max_length=50,
                    ),
                ),
                (
                    "instanciacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="componentes",
                        to="ric.instantiation",
                    ),
                ),
            ],
            options={
                "verbose_name": "componente estructural (F03)",
                "verbose_name_plural": "componentes estructurales (F03)",
                "ordering": ["pagina", "orden"],
            },
        ),
    ]
