# Generated by Django 5.2.17 on 2026-09-27 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0008_componenteestructural"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventoric",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("extraccion_texto", "Extracción de texto (OCR)"),
                    ("propuesta_ia", "Propuesta generada por IA"),
                    ("validacion_humana", "Validación humana"),
                    ("segmentacion", "Segmentación en documento nuevo (F04)"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="PropuestaSegmentacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pagina_inicio", models.PositiveIntegerField()),
                ("pagina_fin", models.PositiveIntegerField()),
                ("titulo_detectado", models.CharField(blank=True, max_length=500)),
                ("confianza", models.FloatField()),
                ("regla", models.CharField(max_length=50)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de validación"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=12,
                    ),
                ),
                ("motivo_decision", models.TextField(blank=True)),
                ("fecha_validacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "instanciacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propuestas_segmentacion",
                        to="ric.instantiation",
                    ),
                ),
                (
                    "instanciacion_creada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ric.instantiation",
                    ),
                ),
                (
                    "record_creado",
                    models.ForeignKey(
                        blank=True,
                        help_text="El Record creado al aceptar esta propuesta (vacío si está pendiente o fue rechazada).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ric.record",
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segmentaciones_validadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "propuesta de segmentación (F04)",
                "verbose_name_plural": "propuestas de segmentación (F04)",
                "ordering": ["instanciacion", "pagina_inicio"],
            },
        ),
    ]
