# Generated by Django 5.2.17 on 2026-09-27 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0009_alter_eventoric_tipo_propuestasegmentacion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instantiation",
            options={
                "verbose_name": "ingesta de un documento (F01/F02) — Instantiation",
                "verbose_name_plural": "ingesta de documentos (F01/F02) — Instantiation",
            },
        ),
    ]
