# Generated by Django 5.2.17 on 2026-09-28 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ric", "0010_alter_instantiation_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="VersionRiC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "datos_anteriores",
                    models.JSONField(
                        help_text="Campos propios (sin relaciones) tal como estaban antes de este cambio."
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "versión (historial RiC)",
                "verbose_name_plural": "versiones (historial RiC)",
                "ordering": ["-fecha"],
            },
        ),
    ]
