# Generated by Django 5.2.17 on 2026-09-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0011_versionric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventoric",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("extraccion_texto", "Extracción de texto (OCR)"),
                    ("propuesta_ia", "Propuesta generada por IA"),
                    ("validacion_humana", "Validación humana"),
                    ("segmentacion", "Segmentación en documento nuevo (F04)"),
                    ("fusion_entidades", "Fusión de dos entidades duplicadas (F08)"),
                ],
                max_length=30,
            ),
        ),
    ]
