# Generated by Django 5.2.17 on 2026-09-29 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0012_alter_eventoric_tipo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instantiation",
            options={
                "verbose_name": "ingesta de un documento (M1/M2) — Instantiation",
                "verbose_name_plural": "ingesta de documentos (M1/M2) — Instantiation",
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="RF-M5-04: quién creó esta entrada (vacío si la creó el sistema).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="RF-M5-04: quién hizo la última modificación.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="serie_trd",
            field=models.CharField(
                blank=True,
                help_text="RF-M5-03: serie o subserie de la Tabla de Retención Documental vigente con la que se vincula esta entrada de autoridad.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="date",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="RF-M5-04: quién creó esta entrada (vacío si la creó el sistema).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="date",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="RF-M5-04: quién hizo la última modificación.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="date",
            name="serie_trd",
            field=models.CharField(
                blank=True,
                help_text="RF-M5-03: serie o subserie de la Tabla de Retención Documental vigente con la que se vincula esta entrada de autoridad.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="RF-M5-04: quién creó esta entrada (vacío si la creó el sistema).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="RF-M5-04: quién hizo la última modificación.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="serie_trd",
            field=models.CharField(
                blank=True,
                help_text="RF-M5-03: serie o subserie de la Tabla de Retención Documental vigente con la que se vincula esta entrada de autoridad.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="condicion_acceso",
            field=models.CharField(
                choices=[
                    ("abierto", "Abierto"),
                    ("restringido", "Restringido"),
                    ("reservado", "Reservado"),
                ],
                default="abierto",
                help_text="Clasificación de acceso a la información (Ley 1712 de 2014); la decide el equipo archivístico. RF-M8-04: el rol consulta solo ve documentos con todas sus instanciaciones abiertas.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="RF-M5-04: quién creó esta entrada (vacío si la creó el sistema).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="formato",
            field=models.CharField(
                blank=True,
                help_text="RF-M1-03: extensión detectada al cargar (pdf, docx, png...).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="idioma_detectado",
            field=models.CharField(
                blank=True,
                help_text="RF-M2-03: código del idioma detectado en el texto extraído.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="RF-M5-04: quién hizo la última modificación.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="serie_trd",
            field=models.CharField(
                blank=True,
                help_text="RF-M5-03: serie o subserie de la Tabla de Retención Documental vigente con la que se vincula esta entrada de autoridad.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="tamano_bytes",
            field=models.BigIntegerField(
                blank=True,
                help_text="RF-M1-03: tamaño del archivo al cargar.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="tipo_copia",
            field=models.CharField(
                choices=[
                    ("master_preservacion", "Máster de preservación"),
                    ("copia_acceso", "Copia de acceso"),
                ],
                default="copia_acceso",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paginatexto",
            name="calidad_aceptada",
            field=models.BooleanField(
                blank=True,
                help_text="RF-M2-04: decisión sobre una página de calidad baja — True 'aceptar igual', False 'reescanear', vacío sin decidir.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="RF-M5-04: quién creó esta entrada (vacío si la creó el sistema).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="RF-M5-04: quién hizo la última modificación.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="serie_trd",
            field=models.CharField(
                blank=True,
                help_text="RF-M5-03: serie o subserie de la Tabla de Retención Documental vigente con la que se vincula esta entrada de autoridad.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="propuestaric",
            name="datos_extra",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Lo que el motor propuso además del nombre: rol del agente en el documento, fecha normalizada y precisión, tipo de norma, tipo de lugar y código DANE, entrada de vocabulario sugerida.",
            ),
        ),
        migrations.AddField(
            model_name="recordresource",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="RF-M5-04: quién creó esta entrada (vacío si la creó el sistema).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recordresource",
            name="fecha_publicacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recordresource",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="RF-M5-04: quién hizo la última modificación.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recordresource",
            name="publicado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recordresource",
            name="publicado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recordresource",
            name="serie_trd",
            field=models.CharField(
                blank=True,
                help_text="RF-M5-03: serie o subserie de la Tabla de Retención Documental vigente con la que se vincula esta entrada de autoridad.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="relacionric",
            name="motivo_decision",
            field=models.TextField(
                blank=True,
                help_text="M4/M6: por qué se retiró o rechazó esta relación (queda en el historial).",
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="RF-M5-04: quién creó esta entrada (vacío si la creó el sistema).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="RF-M5-04: quién hizo la última modificación.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="serie_trd",
            field=models.CharField(
                blank=True,
                help_text="RF-M5-03: serie o subserie de la Tabla de Retención Documental vigente con la que se vincula esta entrada de autoridad.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="eventoric",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("extraccion_texto", "Extracción de texto (OCR)"),
                    ("propuesta_ia", "Propuesta generada por IA"),
                    ("validacion_humana", "Validación humana"),
                    ("segmentacion", "Segmentación en documento nuevo (F04)"),
                    ("fusion_entidades", "Fusión de dos entidades duplicadas (F08)"),
                    ("ingesta", "Carga de un archivo (M1)"),
                    ("relacion_editada", "Relación corregida o retirada (M4)"),
                    ("publicacion", "Aprobación y publicación en el catálogo (M6)"),
                    ("exportacion", "Exportación (M9)"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ConfiguracionSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dias_limite_revision",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="RF-M10-04: días tras los cuales un documento pendiente de revisión genera alerta.",
                    ),
                ),
                (
                    "umbral_calidad_ocr",
                    models.FloatField(
                        default=60.0,
                        help_text="RF-M2-04: confianza media de OCR (0-100) por debajo de la cual una página se marca 'calidad baja'.",
                    ),
                ),
                (
                    "umbral_confianza_revision",
                    models.FloatField(
                        default=0.7,
                        help_text="CC-04: confianza (0-1) por debajo de la cual una ficha se marca de baja confianza en análisis y revisión.",
                    ),
                ),
                (
                    "umbral_similitud_vocabulario",
                    models.FloatField(
                        default=0.8,
                        help_text="CC-05: similitud (0-1) a partir de la cual se propone reutilizar una entrada del vocabulario en vez de crear una nueva.",
                    ),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "configuración del sistema",
                "verbose_name_plural": "configuración del sistema",
            },
        ),
        migrations.CreateModel(
            name="Exportacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "formato",
                    models.CharField(
                        choices=[
                            ("rdf", "RDF/RiC-O (Turtle)"),
                            ("json-ld", "JSON-LD"),
                            ("csv", "CSV (tabular)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "documentos",
                    models.JSONField(
                        default=list, help_text="IDs de los Record exportados."
                    ),
                ),
                ("total_registros", models.PositiveIntegerField(default=0)),
                ("archivo", models.FileField(upload_to="ric/exportaciones/%Y/%m/")),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exportaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "exportación (M9)",
                "verbose_name_plural": "exportaciones (M9)",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="FormaDocumental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("definicion", models.TextField(blank=True)),
                (
                    "serie_trd",
                    models.CharField(
                        blank=True,
                        help_text="Serie o subserie de la Tabla de Retención Documental a la que corresponde este tipo.",
                        max_length=255,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "forma documental",
                "verbose_name_plural": "formas documentales",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="record",
            name="forma_documental",
            field=models.ForeignKey(
                blank=True,
                help_text="RiC-A17 como entrada controlada del vocabulario de formas documentales (M5).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="ric.formadocumental",
            ),
        ),
        migrations.CreateModel(
            name="ProveedorIAConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proveedor",
                    models.CharField(
                        choices=[
                            ("gemini", "Gemini (Google, en la nube)"),
                            ("claude", "Claude (Anthropic, en la nube)"),
                            ("local-spacy", "IA local (spaCy, sin salir del servidor)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        blank=True,
                        help_text="Vacío = el modelo por defecto del proveedor.",
                        max_length=100,
                    ),
                ),
                (
                    "clave_api",
                    models.CharField(
                        blank=True,
                        help_text="Vacío = usar la variable de entorno del servidor.",
                        max_length=500,
                    ),
                ),
                ("activo", models.BooleanField(default=False)),
                ("ultima_prueba", models.DateTimeField(blank=True, null=True)),
                ("prueba_exitosa", models.BooleanField(blank=True, null=True)),
                ("mensaje_prueba", models.TextField(blank=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "proveedor de IA (M11)",
                "verbose_name_plural": "proveedores de IA (M11)",
                "ordering": ["-activo", "proveedor"],
            },
        ),
    ]
