# Generated by Django 5.2.17 on 2026-09-29 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0013_modulos_m1_m11"),
    ]

    operations = [
        migrations.AddField(
            model_name="formadocumental",
            name="disposicion_final",
            field=models.CharField(
                blank=True,
                choices=[
                    ("conservacion_total", "Conservación total"),
                    ("eliminacion", "Eliminación"),
                    ("seleccion", "Selección"),
                    ("digitalizacion", "Digitalización"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="formadocumental",
            name="tiempo_retencion_archivo_central",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Años en archivo central, según la TRD.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formadocumental",
            name="tiempo_retencion_archivo_gestion",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Años en archivo de gestión, según la TRD.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="instanciacion_origen",
            field=models.ForeignKey(
                blank=True,
                help_text="La instanciación de la que esta se deriva por migración o conversión de formato (RiC-R015: una copia de preservación PDF/A generada desde el TIFF original), nunca una sustitución silenciosa del original.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derivadas",
                to="ric.instantiation",
            ),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="nota_autenticidad",
            field=models.TextField(
                blank=True,
                help_text="Mecanismos de verificación además de la huella SHA-256: firma digital, sello de tiempo, cadena de custodia.",
            ),
        ),
    ]
