# Generated by Django 5.2.17 on 2026-09-29 02:32
#
# Especificación funcional RIC v3, "corrección de una propuesta anterior":
# la retención y la disposición final varían serie por serie, no por forma
# documental. Se mueven al Mandato (RiC-E17) y cada serie de la TRD pasa a
# ser una Actividad vinculada a su Mandato. Los valores que ya estuvieran
# guardados en una forma documental se trasladan antes de borrar las
# columnas, para no perder lo cargado desde la pantalla de vocabularios.

import django.db.models.deletion
from django.db import migrations, models

_DISPOSICION_A_CAMPO = {
    "conservacion_total": "conservacion_total",
    "eliminacion": "eliminacion",
    "seleccion": "seleccion",
    "digitalizacion": "medio_tecnologico",
}


def trasladar_retencion_a_mandato(apps, schema_editor):
    FormaDocumental = apps.get_model("ric", "FormaDocumental")
    Mandate = apps.get_model("ric", "Mandate")
    Activity = apps.get_model("ric", "Activity")

    for forma in FormaDocumental.objects.all():
        tiene_datos = (
            forma.tiempo_retencion_archivo_gestion is not None
            or forma.tiempo_retencion_archivo_central is not None
            or forma.disposicion_final
        )
        if not tiene_datos:
            continue
        serie = (forma.serie_trd or "").strip() or f"Serie de «{forma.nombre}»"
        mandato = Mandate.objects.filter(nombre=f"TRD · {serie}").first()
        if mandato is None:
            mandato = Mandate.objects.create(
                nombre=f"TRD · {serie}",
                tipo_mandato="Tabla de Retención Documental",
                descripcion_general="Serie de la TRD trasladada desde la forma documental (especificación v3).",
                creado_por=forma.creado_por,
                serie_trd=serie,
            )
        mandato.tiempo_retencion_archivo_gestion = forma.tiempo_retencion_archivo_gestion
        mandato.tiempo_retencion_archivo_central = forma.tiempo_retencion_archivo_central
        campo = _DISPOSICION_A_CAMPO.get(forma.disposicion_final)
        if campo:
            setattr(mandato, campo, True)
        mandato.save()

        actividad = Activity.objects.filter(nombre=serie, mandato=mandato).first()
        if actividad is None:
            actividad = Activity.objects.create(
                nombre=serie, mandato=mandato, creado_por=forma.creado_por, serie_trd=serie,
                tipo_actividad="serie TRD",
            )
        actividad.formas_documentales.add(forma)


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0014_retencion_autenticidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandate",
            name="codigo_serie",
            field=models.CharField(blank=True, help_text="Código de la serie en la TRD.", max_length=20),
        ),
        migrations.AddField(
            model_name="mandate",
            name="codigo_subserie",
            field=models.CharField(blank=True, help_text="Código de la subserie en la TRD, si aplica.", max_length=20),
        ),
        migrations.AddField(
            model_name="mandate",
            name="conservacion_total",
            field=models.BooleanField(default=False, help_text="Disposición final CT."),
        ),
        migrations.AddField(
            model_name="mandate",
            name="eliminacion",
            field=models.BooleanField(default=False, help_text="Disposición final E."),
        ),
        migrations.AddField(
            model_name="mandate",
            name="medio_tecnologico",
            field=models.BooleanField(default=False, help_text="Disposición final MT (medio tecnológico / digitalización)."),
        ),
        migrations.AddField(
            model_name="mandate",
            name="seleccion",
            field=models.BooleanField(default=False, help_text="Disposición final S."),
        ),
        migrations.AddField(
            model_name="mandate",
            name="procedimiento",
            field=models.TextField(blank=True, help_text="Columna 'Procedimiento' de la TRD: qué se hace al vencer la retención."),
        ),
        migrations.AddField(
            model_name="mandate",
            name="soporte",
            field=models.CharField(blank=True, help_text="Soporte según la TRD: papel, electrónico...", max_length=100),
        ),
        migrations.AddField(
            model_name="mandate",
            name="tiempo_retencion_archivo_central",
            field=models.PositiveIntegerField(blank=True, help_text="Años en archivo central, según la TRD.", null=True),
        ),
        migrations.AddField(
            model_name="mandate",
            name="tiempo_retencion_archivo_gestion",
            field=models.PositiveIntegerField(blank=True, help_text="Años en archivo de gestión, según la TRD.", null=True),
        ),
        migrations.AddField(
            model_name="mandate",
            name="vigencia",
            field=models.DateField(blank=True, help_text="Fecha de vigencia/aprobación de la TRD de la que sale esta serie.", null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="mandato",
            field=models.ForeignKey(
                blank=True,
                help_text="La serie/subserie de la TRD que regula esta función (caso común de RiC-R063 'regulates or regulated').",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actividades",
                to="ric.mandate",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="formas_documentales",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tipos documentales que produce esta serie según la TRD (RF-M5-03).",
                related_name="actividades",
                to="ric.formadocumental",
            ),
        ),
        migrations.RunPython(trasladar_retencion_a_mandato, migrations.RunPython.noop),
        migrations.RemoveField(model_name="formadocumental", name="disposicion_final"),
        migrations.RemoveField(model_name="formadocumental", name="tiempo_retencion_archivo_central"),
        migrations.RemoveField(model_name="formadocumental", name="tiempo_retencion_archivo_gestion"),
    ]
