# Generated by Django 5.2.17 on 2026-09-29 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0015_retencion_en_mandato"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordset",
            name="actividad",
            field=models.ForeignKey(
                blank=True,
                help_text="Para una serie/subserie: la función de la TRD que este conjunto documenta (caso común de RiC-R033 'documents'); por ella hereda la retención del Mandato.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conjuntos",
                to="ric.activity",
            ),
        ),
        migrations.AddField(
            model_name="recordset",
            name="fecha_apertura",
            field=models.DateField(
                blank=True,
                help_text="Expediente: fecha del primer documento.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recordset",
            name="fecha_cierre",
            field=models.DateField(
                blank=True,
                help_text="Expediente: fecha de cierre del trámite. Desde aquí corre la retención en archivo de gestión.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recordset",
            name="tipo_conjunto",
            field=models.CharField(
                blank=True,
                help_text="RiC-A36 Record Set Type: fondo, sección, serie, subserie, expediente, colección...",
                max_length=50,
            ),
        ),
    ]
