# Generated by Django 5.2.17 on 2026-09-29 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0016_expedientes_y_series"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="nombres_alternativos",
            field=models.TextField(
                blank=True,
                help_text="Variantes con las que el agente aparece en distintos documentos, una por línea (especificación v5; en RiC-O serían otros rico:Name del mismo agente).",
            ),
        ),
        migrations.AddField(
            model_name="propuestaric",
            name="mecanismo",
            field=models.ForeignKey(
                blank=True,
                help_text="RiC-E13: el motor de análisis (proveedor y versión del modelo) como agente propio del grafo, para trazar qué propuso cada versión (especificación v5).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="propuestas",
                to="ric.mechanism",
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="enlace_texto_completo",
            field=models.URLField(
                blank=True,
                help_text="Referencia o enlace al texto normativo completo.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="fecha_expedicion",
            field=models.DateField(
                blank=True,
                help_text="Fecha de expedición de la norma (especificación v5).",
                null=True,
            ),
        ),
    ]
