# Generated by Django 5.2.17 on 2026-09-29 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ric", "0017_alineacion_v5"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario_nombre", models.CharField(blank=True, max_length=150)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("iniciar_sesion", "Inicio de sesión"),
                            ("cerrar_sesion", "Cierre de sesión"),
                            ("login_fallido", "Intento de inicio de sesión fallido"),
                            (
                                "bloqueo_login",
                                "Inicio de sesión bloqueado por intentos",
                            ),
                            ("acceso_denegado", "Acceso denegado por rol"),
                            ("crear", "Creación"),
                            ("modificar", "Modificación"),
                            ("eliminar", "Borrado lógico"),
                            ("restaurar", "Restauración"),
                            ("sesiones_cerradas", "Sesiones revocadas"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("objeto_texto", models.CharField(blank=True, max_length=255)),
                ("antes", models.JSONField(blank=True, default=dict)),
                ("despues", models.JSONField(blank=True, default=dict)),
                ("detalle", models.JSONField(blank=True, default=dict)),
                ("exitoso", models.BooleanField(default=True)),
                ("ip", models.CharField(blank=True, max_length=45)),
                ("agente_usuario", models.CharField(blank=True, max_length=255)),
                ("fecha", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "registro de auditoría",
                "verbose_name_plural": "registros de auditoría",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="eliminado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="agent",
            name="eliminado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="motivo_eliminacion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="date",
            name="eliminado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="date",
            name="eliminado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="date",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="date",
            name="motivo_eliminacion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="eliminado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="eliminado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="motivo_eliminacion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="formadocumental",
            name="eliminado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="formadocumental",
            name="eliminado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formadocumental",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="formadocumental",
            name="motivo_eliminacion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="eliminado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="eliminado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="motivo_eliminacion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="place",
            name="eliminado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="place",
            name="eliminado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="motivo_eliminacion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="proveedoriaconfig",
            name="eliminado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="proveedoriaconfig",
            name="eliminado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proveedoriaconfig",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="proveedoriaconfig",
            name="motivo_eliminacion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recordresource",
            name="eliminado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="recordresource",
            name="eliminado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recordresource",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recordresource",
            name="motivo_eliminacion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="relacionric",
            name="eliminado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="relacionric",
            name="eliminado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relacionric",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="relacionric",
            name="motivo_eliminacion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="eliminado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="rule",
            name="eliminado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="motivo_eliminacion",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="formadocumental",
            name="nombre",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="formadocumental",
            constraint=models.UniqueConstraint(
                condition=models.Q(("eliminado", False)),
                fields=("nombre",),
                name="forma_documental_nombre_unico_activa",
            ),
        ),
        migrations.AddField(
            model_name="registroauditoria",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="registroauditoria",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acciones_auditadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
