# Generated by Django 5.2.17 on 2026-09-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0018_modulo0_seguridad_auditoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="instantiation",
            name="tipo_mime",
            field=models.CharField(
                blank=True,
                help_text="Formato técnico (tipo MIME) verificado contra el contenido al cargar.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("iniciar_sesion", "Inicio de sesión"),
                    ("cerrar_sesion", "Cierre de sesión"),
                    ("login_fallido", "Intento de inicio de sesión fallido"),
                    ("bloqueo_login", "Inicio de sesión bloqueado por intentos"),
                    ("acceso_denegado", "Acceso denegado por rol"),
                    ("crear", "Creación"),
                    ("modificar", "Modificación"),
                    ("eliminar", "Borrado lógico"),
                    ("restaurar", "Restauración"),
                    ("sesiones_cerradas", "Sesiones revocadas"),
                    ("consultar", "Consulta de un documento en el visor"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
