# Generated by Django 5.2.17 on 2026-09-29 14:04

from django.db import migrations, models


def estado_inicial(apps, schema_editor):
    """Los archivos ya preprocesados antes de la cola quedan en listo o
    calidad baja según su última lectura; los demás, sin enviar."""
    Instantiation = apps.get_model("ric", "Instantiation")
    EventoRiC = apps.get_model("ric", "EventoRiC")
    Config = apps.get_model("ric", "ConfiguracionSistema")
    config = Config.objects.filter(pk=1).first()
    umbral = config.umbral_calidad_ocr if config else 60.0
    procesadas = set(EventoRiC.objects.filter(tipo="extraccion_texto", instanciacion__isnull=False).values_list("instanciacion_id", flat=True))
    for inst in Instantiation.objects.filter(pk__in=procesadas):
        baja = inst.paginas.filter(uso_ocr=True, confianza_ocr__lt=umbral, calidad_aceptada__isnull=True).exists()
        Instantiation.objects.filter(pk=inst.pk).update(estado_proceso="calidad_baja" if baja else "listo", progreso=100)


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0019_modulo1_tipo_mime"),
    ]

    operations = [
        migrations.AddField(
            model_name="instantiation",
            name="estado_proceso",
            field=models.CharField(
                choices=[
                    ("sin_enviar", "Sin enviar"),
                    ("en_cola", "En cola"),
                    ("procesando", "Procesando"),
                    ("listo", "Listo"),
                    ("calidad_baja", "Calidad baja"),
                    ("error", "Error"),
                ],
                db_index=True,
                default="sin_enviar",
                editable=False,
                max_length=14,
            ),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="etapa",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Etapa en curso: OCR página n de m, idioma, motor de análisis.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="intentos",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="mensaje_proceso",
            field=models.TextField(
                blank=True, editable=False, help_text="Resultado o error explicado en lenguaje claro."
            ),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="proceso_encolado",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="proceso_iniciado",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="proceso_terminado",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="progreso",
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text="0 a 100."),
        ),
        migrations.AddField(
            model_name="instantiation",
            name="resultado_proceso",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.RunPython(estado_inicial, migrations.RunPython.noop),
    ]
