# Generated by Django 5.2.17 on 2026-09-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0020_modulo2_estado_proceso"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedoriaconfig",
            name="es_respaldo",
            field=models.BooleanField(
                default=False,
                help_text="Si el proveedor principal falla (saturado, sin conexión, límite de uso), el motor usa este automáticamente.",
            ),
        ),
        migrations.AlterField(
            model_name="proveedoriaconfig",
            name="proveedor",
            field=models.CharField(
                choices=[
                    ("gemini", "Gemini (Google, en la nube)"),
                    ("claude", "Claude (Anthropic, en la nube)"),
                    ("local-spacy", "IA local (spaCy, sin salir del servidor)"),
                    (
                        "ollama",
                        "IA local con Ollama (modelo de lenguaje en el propio servidor)",
                    ),
                ],
                max_length=20,
            ),
        ),
    ]
