# Generated by Django 5.2.17 on 2026-09-29 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def estado_inicial(apps, schema_editor):
    """Lo estructural (instrumentos y clasificación) no requiere revisión;
    lo de documentos ya publicados cuenta como confirmado por quien los
    publicó, para no devolver a revisión lo que ya estaba en el catálogo."""
    RelacionRiC = apps.get_model("ric", "RelacionRiC")
    Record = apps.get_model("ric", "Record")
    ContentType = apps.get_model("contenttypes", "ContentType")
    RelacionRiC.objects.filter(fuente_relacion="Instrumento archivístico precargado (M5)").update(revision="no_aplica")
    ct = ContentType.objects.filter(app_label="ric", model="record").first()
    if ct is None:
        return
    for record in Record.objects.filter(publicado=True):
        for campo in ("origen", "destino"):
            RelacionRiC.objects.filter(
                **{f"{campo}_content_type": ct, f"{campo}_object_id": record.pk}, revision="pendiente",
                estado__in=("aceptada", "modificada"),
            ).update(revision="confirmada", revisado_por_id=record.publicado_por_id,
                     fecha_revision=record.fecha_publicacion, nota_revision="Publicado antes de la revisión por ficha (M6).")


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0021_ia_local_ollama"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="relacionric",
            name="fecha_revision",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relacionric",
            name="nota_revision",
            field=models.TextField(
                blank=True,
                help_text="M6: qué se corrigió en la revisión o por qué se confirmó.",
            ),
        ),
        migrations.AddField(
            model_name="relacionric",
            name="revisado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="relaciones_revisadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="relacionric",
            name="revision",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente de revisión"),
                    ("confirmada", "Confirmada en revisión"),
                    ("corregida", "Corregida en revisión"),
                    ("no_aplica", "Clasificación archivística (no requiere revisión)"),
                ],
                db_index=True,
                default="pendiente",
                max_length=12,
            ),
        ),
        migrations.RunPython(estado_inicial, migrations.RunPython.noop),
    ]
