# Generated by Django 5.2.17 on 2026-09-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0023_busqueda_sin_tildes"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportacion",
            name="alcance",
            field=models.TextField(
                blank=True,
                help_text="RF-M9-03: qué documentos incluye, en lenguaje claro.",
            ),
        ),
        migrations.AddField(
            model_name="exportacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("en_cola", "En cola"),
                    ("procesando", "Generando"),
                    ("lista", "Lista"),
                    ("error", "Error"),
                ],
                default="lista",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="exportacion",
            name="mensaje",
            field=models.TextField(
                blank=True,
                help_text="Resultado de la validación del archivo o causa del error.",
            ),
        ),
        migrations.AddField(
            model_name="exportacion",
            name="progreso",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="exportacion",
            name="sha256",
            field=models.CharField(
                blank=True,
                help_text="Huella del archivo generado, para verificar la copia entregada.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="exportacion",
            name="tamano_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exportacion",
            name="archivo",
            field=models.FileField(blank=True, upload_to="ric/exportaciones/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("iniciar_sesion", "Inicio de sesión"),
                    ("cerrar_sesion", "Cierre de sesión"),
                    ("login_fallido", "Intento de inicio de sesión fallido"),
                    ("bloqueo_login", "Inicio de sesión bloqueado por intentos"),
                    ("acceso_denegado", "Acceso denegado por rol"),
                    ("crear", "Creación"),
                    ("modificar", "Modificación"),
                    ("eliminar", "Borrado lógico"),
                    ("restaurar", "Restauración"),
                    ("sesiones_cerradas", "Sesiones revocadas"),
                    ("consultar", "Consulta de un documento en el visor"),
                    ("exportar", "Exportación de documentos (M9)"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
