# Generated by Django 5.2.17 on 2026-09-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0024_modulo9_exportacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventoric",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("extraccion_texto", "Extracción de texto (OCR)"),
                    ("propuesta_ia", "Propuesta generada por IA"),
                    ("validacion_humana", "Validación humana"),
                    ("segmentacion", "Segmentación en documento nuevo"),
                    ("fusion_entidades", "Fusión de dos entidades duplicadas"),
                    ("ingesta", "Carga de un archivo"),
                    ("relacion_editada", "Relación corregida o retirada"),
                    ("publicacion", "Aprobación y publicación en el catálogo"),
                    ("exportacion", "Exportación"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("iniciar_sesion", "Inicio de sesión"),
                    ("cerrar_sesion", "Cierre de sesión"),
                    ("login_fallido", "Intento de inicio de sesión fallido"),
                    ("bloqueo_login", "Inicio de sesión bloqueado por intentos"),
                    ("acceso_denegado", "Acceso denegado por rol"),
                    ("crear", "Creación"),
                    ("modificar", "Modificación"),
                    ("eliminar", "Borrado lógico"),
                    ("restaurar", "Restauración"),
                    ("sesiones_cerradas", "Sesiones revocadas"),
                    ("consultar", "Consulta de un documento en el visor"),
                    ("exportar", "Exportación de documentos"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
