# Generated by Django 5.2.17 on 2026-09-29 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0026_retirar_datos_de_prueba"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("iniciar_sesion", "Inicio de sesión"),
                    ("cerrar_sesion", "Cierre de sesión"),
                    ("login_fallido", "Intento de inicio de sesión fallido"),
                    ("bloqueo_login", "Inicio de sesión bloqueado por intentos"),
                    ("acceso_denegado", "Acceso denegado por rol"),
                    ("crear", "Creación"),
                    ("modificar", "Modificación"),
                    ("eliminar", "Borrado lógico"),
                    ("restaurar", "Restauración"),
                    ("sesiones_cerradas", "Sesiones revocadas"),
                    ("consultar", "Consulta de un documento en el visor"),
                    ("exportar", "Exportación de documentos"),
                    (
                        "solicitar_restablecimiento",
                        "Solicitud de restablecimiento de contraseña",
                    ),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="SolicitudRestablecimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("atendida", models.BooleanField(default=False)),
                ("atendida_en", models.DateTimeField(blank=True, null=True)),
                (
                    "via",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("correo", "Enlace enviado por correo"),
                            ("administrador", "Enlace generado por el administrador"),
                            ("contrasena", "La persona creó su contraseña"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "atendida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_restablecimiento",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "solicitud de restablecimiento de contraseña",
                "verbose_name_plural": "solicitudes de restablecimiento de contraseña",
                "ordering": ["-fecha"],
            },
        ),
    ]
