# Generated by Django 5.2.17 on 2026-09-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ric", "0027_solicitud_restablecimiento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitudrestablecimiento",
            name="via",
            field=models.CharField(
                blank=True,
                choices=[
                    ("correo", "Enlace enviado por correo"),
                    ("administrador", "Enlace generado por el administrador"),
                    ("contrasena", "La persona creó su contraseña"),
                    ("ingreso", "La persona volvió a ingresar con su contraseña"),
                    ("descartada", "Descartada por el administrador"),
                ],
                max_length=20,
            ),
        ),
    ]
