"""autenticacion y auditoria

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 18:04:09.236193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=254), nullable=False),
    sa.Column('rol', sa.Enum('archivista', 'revisor', 'consulta', 'administrador', name='rol_usuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=True),
    sa.Column('contrasena_cambiada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creado_por_id', sa.UUID(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_table('registro_auditoria',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('modulo', sa.String(length=40), nullable=False),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=60), nullable=True),
    sa.Column('entidad_id', sa.String(length=64), nullable=True),
    sa.Column('valor_anterior', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valor_nuevo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_auditoria_accion'), 'registro_auditoria', ['accion'], unique=False)
    op.create_index(op.f('ix_registro_auditoria_entidad_id'), 'registro_auditoria', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_registro_auditoria_fecha'), 'registro_auditoria', ['fecha'], unique=False)
    op.create_index(op.f('ix_registro_auditoria_modulo'), 'registro_auditoria', ['modulo'], unique=False)
    op.create_index(op.f('ix_registro_auditoria_usuario_id'), 'registro_auditoria', ['usuario_id'], unique=False)
    op.create_table('sesiones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('huella_renovacion', sa.String(length=64), nullable=False),
    sa.Column('iniciada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultima_actividad', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vence_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cerrada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_cierre', sa.Enum('cierre_voluntario', 'expiracion', 'revocada_administrador', 'cambio_contrasena', 'cuenta_desactivada', 'reutilizacion_token', name='motivo_cierre_sesion'), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('navegador', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_cerrada_en'), 'sesiones', ['cerrada_en'], unique=False)
    op.create_index(op.f('ix_sesiones_usuario_id'), 'sesiones', ['usuario_id'], unique=False)
    op.create_table('tokens_un_uso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('invitacion', 'recuperacion', name='tipo_token'), nullable=False),
    sa.Column('huella', sa.String(length=64), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vence_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anulado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_solicitud', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('huella')
    )
    op.create_index(op.f('ix_tokens_un_uso_usuario_id'), 'tokens_un_uso', ['usuario_id'], unique=False)
    # ### end Alembic commands ###

    # El registro de auditoría es de solo anexar: la base de datos misma
    # rechaza cualquier modificación o borrado, venga de donde venga.
    op.execute("""
        CREATE FUNCTION auditoria_solo_anexar() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'El registro de auditoría no se puede modificar ni borrar.';
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER registro_auditoria_inmutable
        BEFORE UPDATE OR DELETE ON registro_auditoria
        FOR EACH ROW EXECUTE FUNCTION auditoria_solo_anexar();
    """)
    op.execute("""
        CREATE TRIGGER registro_auditoria_sin_vaciar
        BEFORE TRUNCATE ON registro_auditoria
        FOR EACH STATEMENT EXECUTE FUNCTION auditoria_solo_anexar();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS registro_auditoria_sin_vaciar ON registro_auditoria")
    op.execute("DROP TRIGGER IF EXISTS registro_auditoria_inmutable ON registro_auditoria")
    op.execute("DROP FUNCTION IF EXISTS auditoria_solo_anexar()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_un_uso_usuario_id'), table_name='tokens_un_uso')
    op.drop_table('tokens_un_uso')
    op.drop_index(op.f('ix_sesiones_usuario_id'), table_name='sesiones')
    op.drop_index(op.f('ix_sesiones_cerrada_en'), table_name='sesiones')
    op.drop_table('sesiones')
    op.drop_index(op.f('ix_registro_auditoria_usuario_id'), table_name='registro_auditoria')
    op.drop_index(op.f('ix_registro_auditoria_modulo'), table_name='registro_auditoria')
    op.drop_index(op.f('ix_registro_auditoria_fecha'), table_name='registro_auditoria')
    op.drop_index(op.f('ix_registro_auditoria_entidad_id'), table_name='registro_auditoria')
    op.drop_index(op.f('ix_registro_auditoria_accion'), table_name='registro_auditoria')
    op.drop_table('registro_auditoria')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
    for tipo in ("tipo_token", "motivo_cierre_sesion", "rol_usuario"):
        op.execute(f"DROP TYPE IF EXISTS {tipo}")
