"""ingesta

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 18:56:05.980822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametros',
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('valor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_por_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('recursos_documentales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nivel', sa.Enum('fondo', 'seccion', 'serie', 'subserie', 'expediente', 'unidad_documental', name='nivel_descripcion'), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('fechas_extremas', sa.String(length=60), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('incluido_en_id', sa.UUID(), nullable=True),
    sa.Column('fondo_id', sa.UUID(), nullable=True),
    sa.Column('creado_por_id', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['fondo_id'], ['recursos_documentales.id'], ),
    sa.ForeignKeyConstraint(['incluido_en_id'], ['recursos_documentales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recursos_documentales_fondo_id'), 'recursos_documentales', ['fondo_id'], unique=False)
    op.create_index(op.f('ix_recursos_documentales_incluido_en_id'), 'recursos_documentales', ['incluido_en_id'], unique=False)
    op.create_index(op.f('ix_recursos_documentales_nivel'), 'recursos_documentales', ['nivel'], unique=False)
    op.create_table('alertas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('severidad', sa.Enum('alta', 'media', 'baja', name='severidad_alerta'), nullable=False),
    sa.Column('modulo', sa.String(length=40), nullable=False),
    sa.Column('fondo_id', sa.UUID(), nullable=True),
    sa.Column('entidad_tipo', sa.String(length=60), nullable=False),
    sa.Column('entidad_id', sa.String(length=64), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=False),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atendida_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atendida_por_id', sa.UUID(), nullable=True),
    sa.Column('nota_atencion', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['atendida_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['fondo_id'], ['recursos_documentales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_fondo_id'), 'alertas', ['fondo_id'], unique=False)
    op.create_index(op.f('ix_alertas_tipo'), 'alertas', ['tipo'], unique=False)
    op.create_index('ux_alerta_pendiente', 'alertas', ['tipo', 'entidad_id'], unique=True, postgresql_where=sa.text('atendida_en IS NULL'))
    op.create_table('instanciaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fondo_id', sa.UUID(), nullable=False),
    sa.Column('expediente_destino_id', sa.UUID(), nullable=True),
    sa.Column('nombre_original', sa.String(length=500), nullable=False),
    sa.Column('ruta', sa.String(length=500), nullable=False),
    sa.Column('tamano_bytes', sa.BigInteger(), nullable=False),
    sa.Column('tipo_declarado', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.Enum('procesando', 'duplicado_pendiente', 'error', 'listo_para_descripcion', name='estado_ingesta'), nullable=False),
    sa.Column('paso', sa.Enum('en_espera', 'huella', 'duplicados', 'formato', 'texto', 'terminado', name='paso_proceso'), nullable=False),
    sa.Column('progreso', sa.Integer(), nullable=False),
    sa.Column('detalle_paso', sa.String(length=200), nullable=True),
    sa.Column('tomado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('mensaje_error', sa.String(length=500), nullable=True),
    sa.Column('huella', sa.String(length=64), nullable=True),
    sa.Column('algoritmo_huella', sa.String(length=20), nullable=False),
    sa.Column('duplicado_de_id', sa.UUID(), nullable=True),
    sa.Column('duplicado_confirmado', sa.Boolean(), nullable=False),
    sa.Column('formato_puid', sa.String(length=40), nullable=True),
    sa.Column('formato_nombre', sa.String(length=300), nullable=True),
    sa.Column('formato_version', sa.String(length=100), nullable=True),
    sa.Column('formato_mime', sa.String(length=200), nullable=True),
    sa.Column('formato_base', sa.String(length=500), nullable=True),
    sa.Column('formato_no_identificado', sa.Boolean(), nullable=False),
    sa.Column('herramienta_identificacion', sa.String(length=200), nullable=True),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('origen_texto', sa.Enum('capa_de_texto', 'ocr', 'sin_texto', name='origen_texto'), nullable=True),
    sa.Column('paginas', sa.Integer(), nullable=True),
    sa.Column('cargado_por_id', sa.UUID(), nullable=True),
    sa.Column('cargado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('procesado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cargado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['duplicado_de_id'], ['instanciaciones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expediente_destino_id'], ['recursos_documentales.id'], ),
    sa.ForeignKeyConstraint(['fondo_id'], ['recursos_documentales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instanciaciones_cargado_en'), 'instanciaciones', ['cargado_en'], unique=False)
    op.create_index(op.f('ix_instanciaciones_estado'), 'instanciaciones', ['estado'], unique=False)
    op.create_index('ix_instanciaciones_fondo_huella', 'instanciaciones', ['fondo_id', 'huella'], unique=False)
    op.create_index(op.f('ix_instanciaciones_fondo_id'), 'instanciaciones', ['fondo_id'], unique=False)
    op.create_index(op.f('ix_instanciaciones_formato_no_identificado'), 'instanciaciones', ['formato_no_identificado'], unique=False)
    # ### end Alembic commands ###
    # Límite de tamaño por archivo en la ingesta: 500 MB por defecto,
    # ajustable por el administrador.
    op.execute("INSERT INTO parametros (clave, valor, actualizado_en) VALUES ('ingesta_limite_mb', '500', now())")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instanciaciones_formato_no_identificado'), table_name='instanciaciones')
    op.drop_index(op.f('ix_instanciaciones_fondo_id'), table_name='instanciaciones')
    op.drop_index('ix_instanciaciones_fondo_huella', table_name='instanciaciones')
    op.drop_index(op.f('ix_instanciaciones_estado'), table_name='instanciaciones')
    op.drop_index(op.f('ix_instanciaciones_cargado_en'), table_name='instanciaciones')
    op.drop_table('instanciaciones')
    op.drop_index('ux_alerta_pendiente', table_name='alertas', postgresql_where=sa.text('atendida_en IS NULL'))
    op.drop_index(op.f('ix_alertas_tipo'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_fondo_id'), table_name='alertas')
    op.drop_table('alertas')
    op.drop_index(op.f('ix_recursos_documentales_nivel'), table_name='recursos_documentales')
    op.drop_index(op.f('ix_recursos_documentales_incluido_en_id'), table_name='recursos_documentales')
    op.drop_index(op.f('ix_recursos_documentales_fondo_id'), table_name='recursos_documentales')
    op.drop_table('recursos_documentales')
    op.drop_table('parametros')
    # ### end Alembic commands ###
    for tipo in ("origen_texto", "paso_proceso", "estado_ingesta", "severidad_alerta", "nivel_descripcion"):
        op.execute(f"DROP TYPE IF EXISTS {tipo}")
