"""descripcion

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-30 19:55:50.338938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Comparación de nombres por trigramas (servicio de verificación de
    # vocabulario). Extensión de confianza: la puede crear el dueño de la base.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entidades_vocabulario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fondo_id', sa.UUID(), nullable=False),
    sa.Column('clase', sa.Enum('agente', 'lugar', 'forma_documental', name='clase_vocabulario'), nullable=False),
    sa.Column('subtipo', sa.String(length=40), nullable=True),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('nombre_normalizado', sa.String(length=300), nullable=False),
    sa.Column('estado', sa.Enum('activa', 'fusionada', name='estado_entidad_vocabulario'), nullable=False),
    sa.Column('fusionada_en_id', sa.UUID(), nullable=True),
    sa.Column('creado_por_id', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origen', sa.Enum('motor', 'motor_editado', 'persona', name='origen_dato'), nullable=False),
    sa.Column('confianza', sa.Float(), nullable=True),
    sa.Column('motor', sa.String(length=120), nullable=True),
    sa.Column('estado_revision', sa.Enum('validado', name='estado_revision'), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['fondo_id'], ['recursos_documentales.id'], ),
    sa.ForeignKeyConstraint(['fusionada_en_id'], ['entidades_vocabulario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entidades_vocabulario_clase'), 'entidades_vocabulario', ['clase'], unique=False)
    op.create_index(op.f('ix_entidades_vocabulario_fondo_id'), 'entidades_vocabulario', ['fondo_id'], unique=False)
    op.create_index('ix_vocabulario_trigramas', 'entidades_vocabulario', ['nombre_normalizado'], unique=False, postgresql_using='gin', postgresql_ops={'nombre_normalizado': 'gin_trgm_ops'})
    op.create_table('fechas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expresion', sa.String(length=200), nullable=False),
    sa.Column('normalizada', sa.Date(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origen', sa.Enum('motor', 'motor_editado', 'persona', name='origen_dato'), nullable=False),
    sa.Column('confianza', sa.Float(), nullable=True),
    sa.Column('motor', sa.String(length=120), nullable=True),
    sa.Column('estado_revision', sa.Enum('validado', name='estado_revision'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fondo_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origen', sa.Enum('motor', 'motor_editado', 'persona', name='origen_dato'), nullable=False),
    sa.Column('confianza', sa.Float(), nullable=True),
    sa.Column('motor', sa.String(length=120), nullable=True),
    sa.Column('estado_revision', sa.Enum('validado', name='estado_revision'), nullable=False),
    sa.ForeignKeyConstraint(['fondo_id'], ['recursos_documentales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_fondo_id'), 'actividades', ['fondo_id'], unique=False)
    op.create_table('trabajos_descripcion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('fondo_id', sa.UUID(), nullable=False),
    sa.Column('nivel', sa.String(length=40), nullable=False),
    sa.Column('recurso_id', sa.UUID(), nullable=True),
    sa.Column('propuesta', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('abierto', 'publicado', 'cancelado', 'expirado', name='estado_trabajo'), nullable=False),
    sa.Column('iniciado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultima_actividad', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cerrado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fondo_id'], ['recursos_documentales.id'], ),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos_documentales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trabajos_descripcion_estado'), 'trabajos_descripcion', ['estado'], unique=False)
    op.create_index(op.f('ix_trabajos_descripcion_usuario_id'), 'trabajos_descripcion', ['usuario_id'], unique=False)
    op.create_index('ux_trabajo_recurso_abierto', 'trabajos_descripcion', ['recurso_id'], unique=True, postgresql_where=sa.text("estado = 'abierto' AND recurso_id IS NOT NULL"))
    op.create_table('relaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('origen_tipo', sa.String(length=40), nullable=False),
    sa.Column('origen_id', sa.UUID(), nullable=False),
    sa.Column('destino_tipo', sa.String(length=40), nullable=False),
    sa.Column('destino_id', sa.UUID(), nullable=False),
    sa.Column('tipo_relacion', sa.Enum('procedencia', 'asociacion', 'temporal', 'inclusion', 'espacial', 'identidad', name='tipo_relacion'), nullable=False),
    sa.Column('codigo_ric', sa.Enum('has_creator', 'has_author', 'has_accumulator', 'has_receiver', 'has_collector', 'has_sender', 'has_addressee', 'is_or_was_holder_of', 'is_or_was_manager_of', 'is_or_was_owner_of', 'is_or_was_controller_of', 'has_or_had_subordinate', 'has_or_had_subdivision', 'occupies_or_occupied', 'exists_or_existed_in', 'has_or_had_member', 'is_or_was_leader_of', 'includes_or_included', 'has_or_had_constituent', 'is_original_of', 'has_copy', 'has_or_had_derived_instantiation', 'migrated_into', 'regulates_or_regulated', 'is_or_was_expressed_by', 'authorizes', 'is_creation_date_of', 'is_beginning_date_of', 'is_end_date_of', 'is_modification_date_of', 'is_or_was_location_of', 'is_or_was_jurisdiction_of', 'has_or_had_instantiation', 'documents', 'has_or_had_subject', name='codigo_relacion_ric'), nullable=False),
    sa.Column('rol', sa.String(length=40), nullable=True),
    sa.Column('fragmento', sa.Text(), nullable=True),
    sa.Column('fragmento_instanciacion_id', sa.UUID(), nullable=True),
    sa.Column('fragmento_inicio', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('vigente', 'anulada', name='estado_relacion'), nullable=False),
    sa.Column('confirmada_por_id', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anulada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anulada_por_id', sa.UUID(), nullable=True),
    sa.Column('origen', sa.Enum('motor', 'motor_editado', 'persona', name='origen_dato'), nullable=False),
    sa.Column('confianza', sa.Float(), nullable=True),
    sa.Column('motor', sa.String(length=120), nullable=True),
    sa.Column('estado_revision', sa.Enum('validado', name='estado_revision'), nullable=False),
    sa.ForeignKeyConstraint(['anulada_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['confirmada_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['fragmento_instanciacion_id'], ['instanciaciones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relaciones_codigo_ric'), 'relaciones', ['codigo_ric'], unique=False)
    op.create_index(op.f('ix_relaciones_destino_id'), 'relaciones', ['destino_id'], unique=False)
    op.create_index(op.f('ix_relaciones_estado'), 'relaciones', ['estado'], unique=False)
    op.create_index(op.f('ix_relaciones_origen_id'), 'relaciones', ['origen_id'], unique=False)
    op.create_table('trabajo_instanciaciones',
    sa.Column('trabajo_id', sa.UUID(), nullable=False),
    sa.Column('instanciacion_id', sa.UUID(), nullable=False),
    sa.Column('abierto', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instanciacion_id'], ['instanciaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trabajo_id'], ['trabajos_descripcion.id'], ),
    sa.PrimaryKeyConstraint('trabajo_id', 'instanciacion_id')
    )
    op.create_index('ux_instanciacion_en_edicion', 'trabajo_instanciaciones', ['instanciacion_id'], unique=True, postgresql_where=sa.text('abierto'))
    op.add_column('recursos_documentales', sa.Column('alcance_contenido', sa.Text(), nullable=True))
    op.add_column('recursos_documentales', sa.Column('forma_documental_id', sa.UUID(), nullable=True))
    op.add_column('recursos_documentales', sa.Column('origen_titulo', sa.Enum('motor', 'motor_editado', 'persona', name='origen_dato'), nullable=True))
    op.add_column('recursos_documentales', sa.Column('origen_alcance', sa.Enum('motor', 'motor_editado', 'persona', name='origen_dato'), nullable=True))
    op.add_column('recursos_documentales', sa.Column('confianza_alcance', sa.Float(), nullable=True))
    op.add_column('recursos_documentales', sa.Column('motor', sa.String(length=120), nullable=True))
    op.add_column('recursos_documentales', sa.Column('publicado_en', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recursos_documentales', sa.Column('publicado_por_id', sa.UUID(), nullable=True))
    op.add_column('recursos_documentales', sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_recurso_forma_documental', 'recursos_documentales', 'entidades_vocabulario', ['forma_documental_id'], ['id'])
    op.create_foreign_key('fk_recurso_publicado_por', 'recursos_documentales', 'usuarios', ['publicado_por_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_recurso_publicado_por', 'recursos_documentales', type_='foreignkey')
    op.drop_constraint('fk_recurso_forma_documental', 'recursos_documentales', type_='foreignkey')
    op.drop_column('recursos_documentales', 'actualizado_en')
    op.drop_column('recursos_documentales', 'publicado_por_id')
    op.drop_column('recursos_documentales', 'publicado_en')
    op.drop_column('recursos_documentales', 'motor')
    op.drop_column('recursos_documentales', 'confianza_alcance')
    op.drop_column('recursos_documentales', 'origen_alcance')
    op.drop_column('recursos_documentales', 'origen_titulo')
    op.drop_column('recursos_documentales', 'forma_documental_id')
    op.drop_column('recursos_documentales', 'alcance_contenido')
    op.drop_index('ux_instanciacion_en_edicion', table_name='trabajo_instanciaciones', postgresql_where=sa.text('abierto'))
    op.drop_table('trabajo_instanciaciones')
    op.drop_index(op.f('ix_relaciones_origen_id'), table_name='relaciones')
    op.drop_index(op.f('ix_relaciones_estado'), table_name='relaciones')
    op.drop_index(op.f('ix_relaciones_destino_id'), table_name='relaciones')
    op.drop_index(op.f('ix_relaciones_codigo_ric'), table_name='relaciones')
    op.drop_table('relaciones')
    op.drop_index('ux_trabajo_recurso_abierto', table_name='trabajos_descripcion', postgresql_where=sa.text("estado = 'abierto' AND recurso_id IS NOT NULL"))
    op.drop_index(op.f('ix_trabajos_descripcion_usuario_id'), table_name='trabajos_descripcion')
    op.drop_index(op.f('ix_trabajos_descripcion_estado'), table_name='trabajos_descripcion')
    op.drop_table('trabajos_descripcion')
    op.drop_index(op.f('ix_actividades_fondo_id'), table_name='actividades')
    op.drop_table('actividades')
    op.drop_table('fechas')
    op.drop_index('ix_vocabulario_trigramas', table_name='entidades_vocabulario', postgresql_using='gin', postgresql_ops={'nombre_normalizado': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_entidades_vocabulario_fondo_id'), table_name='entidades_vocabulario')
    op.drop_index(op.f('ix_entidades_vocabulario_clase'), table_name='entidades_vocabulario')
    op.drop_table('entidades_vocabulario')
    # ### end Alembic commands ###
    for tipo in ("estado_trabajo", "estado_relacion", "codigo_relacion_ric", "tipo_relacion", "estado_entidad_vocabulario",
                 "clase_vocabulario", "estado_revision", "origen_dato"):
        op.execute(f"DROP TYPE IF EXISTS {tipo}")
