"""vocabularios

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-30 20:32:46.032336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sugerencias_fusion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fondo_id', sa.UUID(), nullable=False),
    sa.Column('clase', postgresql.ENUM('agente', 'lugar', 'forma_documental', name='clase_vocabulario', create_type=False), nullable=False),
    sa.Column('entidad_a_id', sa.UUID(), nullable=False),
    sa.Column('entidad_b_id', sa.UUID(), nullable=False),
    sa.Column('similitud', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobada', 'descartada', 'obsoleta', name='estado_sugerencia'), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resuelta_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resuelta_por_id', sa.UUID(), nullable=True),
    sa.Column('definitiva_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['definitiva_id'], ['entidades_vocabulario.id'], ),
    sa.ForeignKeyConstraint(['entidad_a_id'], ['entidades_vocabulario.id'], ),
    sa.ForeignKeyConstraint(['entidad_b_id'], ['entidades_vocabulario.id'], ),
    sa.ForeignKeyConstraint(['fondo_id'], ['recursos_documentales.id'], ),
    sa.ForeignKeyConstraint(['resuelta_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sugerencias_fusion_estado'), 'sugerencias_fusion', ['estado'], unique=False)
    op.create_index(op.f('ix_sugerencias_fusion_fondo_id'), 'sugerencias_fusion', ['fondo_id'], unique=False)
    op.create_index('ux_sugerencia_par', 'sugerencias_fusion', ['entidad_a_id', 'entidad_b_id'], unique=True)
    op.add_column('relaciones', sa.Column('destino_original_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_relaciones_destino_original_id'), 'relaciones', ['destino_original_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relaciones_destino_original_id'), table_name='relaciones')
    op.drop_column('relaciones', 'destino_original_id')
    op.drop_index('ux_sugerencia_par', table_name='sugerencias_fusion')
    op.drop_index(op.f('ix_sugerencias_fusion_fondo_id'), table_name='sugerencias_fusion')
    op.drop_index(op.f('ix_sugerencias_fusion_estado'), table_name='sugerencias_fusion')
    op.drop_table('sugerencias_fusion')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS estado_sugerencia")
