"""preservacion

Revision ID: 0007
Revises: 0006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migraciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instanciacion_origen_id', sa.UUID(), nullable=False),
    sa.Column('destino', sa.String(length=40), nullable=False),
    sa.Column('destino_nombre', sa.String(length=120), nullable=False),
    sa.Column('modo', sa.Enum('automatica', 'manual', name='modo_migracion'), nullable=False),
    sa.Column('estado', sa.Enum('en_curso', 'completada', 'fallida', 'esperando_archivo', name='estado_migracion'), nullable=False),
    sa.Column('herramienta', sa.String(length=200), nullable=True),
    sa.Column('mensaje', sa.String(length=500), nullable=True),
    sa.Column('aprobada_por_id', sa.UUID(), nullable=False),
    sa.Column('aprobada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('instanciacion_resultado_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['aprobada_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['instanciacion_origen_id'], ['instanciaciones.id'], ),
    sa.ForeignKeyConstraint(['instanciacion_resultado_id'], ['instanciaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migraciones_estado'), 'migraciones', ['estado'], unique=False)
    op.create_index(op.f('ix_migraciones_instanciacion_origen_id'), 'migraciones', ['instanciacion_origen_id'], unique=False)
    op.create_table('verificaciones_integridad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instanciacion_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resultado', sa.Enum('integra', 'alterada', 'ausente', name='resultado_integridad'), nullable=False),
    sa.Column('algoritmo', sa.String(length=20), nullable=False),
    sa.Column('huella_registrada', sa.String(length=64), nullable=True),
    sa.Column('huella_calculada', sa.String(length=64), nullable=True),
    sa.Column('origen', sa.Enum('periodica', 'manual', name='origen_verificacion'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['instanciacion_id'], ['instanciaciones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verificaciones_integridad_fecha'), 'verificaciones_integridad', ['fecha'], unique=False)
    op.create_index(op.f('ix_verificaciones_integridad_instanciacion_id'), 'verificaciones_integridad', ['instanciacion_id'], unique=False)
    estado = sa.Enum('sin_verificar', 'integra', 'alterada', 'ausente', name='estado_integridad')
    estado.create(op.get_bind(), checkfirst=True)
    op.add_column('instanciaciones', sa.Column('estado_integridad', estado, server_default='sin_verificar', nullable=False))
    op.add_column('instanciaciones', sa.Column('ultima_verificacion_en', sa.DateTime(timezone=True), nullable=True))
    op.add_column('instanciaciones', sa.Column('derivada_de_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_instanciaciones_derivada_de_id'), 'instanciaciones', ['derivada_de_id'], unique=False)
    op.create_foreign_key('fk_instanciacion_derivada_de', 'instanciaciones', 'instanciaciones', ['derivada_de_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_instanciacion_derivada_de', 'instanciaciones', type_='foreignkey')
    op.drop_index(op.f('ix_instanciaciones_derivada_de_id'), table_name='instanciaciones')
    op.drop_column('instanciaciones', 'derivada_de_id')
    op.drop_column('instanciaciones', 'ultima_verificacion_en')
    op.drop_column('instanciaciones', 'estado_integridad')
    op.drop_index(op.f('ix_verificaciones_integridad_instanciacion_id'), table_name='verificaciones_integridad')
    op.drop_index(op.f('ix_verificaciones_integridad_fecha'), table_name='verificaciones_integridad')
    op.drop_table('verificaciones_integridad')
    op.drop_index(op.f('ix_migraciones_instanciacion_origen_id'), table_name='migraciones')
    op.drop_index(op.f('ix_migraciones_estado'), table_name='migraciones')
    op.drop_table('migraciones')
    for tipo in ('estado_integridad', 'resultado_integridad', 'origen_verificacion', 'modo_migracion', 'estado_migracion'):
        op.execute(f'DROP TYPE IF EXISTS {tipo}')
    # ### end Alembic commands ###
