"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or "django-insecure-1girjaht^99o!gwh153f)l4rr4)-xw!g-&3_w)$fbu2kxu#jm*"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h]
if DEBUG:
    ALLOWED_HOSTS += ["localhost", "127.0.0.1", "testserver"]

# Dominios propios (p. ej. https://mazuca.example.com) para peticiones POST
# detrás de un proxy (DigitalOcean App Platform / un Droplet con Nginx).
CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o]
if os.environ.get("DJANGO_BEHIND_PROXY") == "1":
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "lineamientos",
    "acervo",
    "asistencia",
    "acceso",
    "ric",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "ric.auditoria_acciones.UsuarioActualMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "ric.roles.contexto_roles",
                "ric.modulos.contexto_modulos",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# RICORA usa siempre PostgreSQL, en desarrollo, en Docker y en producción,
# para probar contra la misma base de datos en todos los entornos. La
# conexión se toma de DATABASE_URL; en desarrollo local (sin Docker), por
# defecto apunta al PostgreSQL de esta máquina con la base "mazuca" creada
# en la Fase de configuración (ver README).
import dj_database_url

DATABASE_URL = os.environ.get(
    "DATABASE_URL", "postgres://mazuca:mazuca@127.0.0.1:5432/mazuca"
)
DATABASES = {"default": dj_database_url.parse(DATABASE_URL)}


# Módulo transversal de seguridad (sección 7 del prompt de desarrollo).
# Contraseñas con bcrypt (las ya guardadas con PBKDF2 siguen valiendo y se
# rehashean al siguiente inicio de sesión).
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]
# Sesión de servidor (no JWT: las pantallas las sirve el mismo servidor):
# expiración corta por inactividad, renovada en cada petición ("refresh"),
# cerrada al cerrar el navegador y revocable desde Administración
# (ric.auditoria_acciones.cerrar_sesiones_de). Las sesiones viven en la base
# de datos, así que la revocación aplica a todos los procesos de inmediato.
SESSION_COOKIE_AGE = int(os.environ.get("RICORA_SESION_MINUTOS", "60")) * 60
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
if os.environ.get("DJANGO_BEHIND_PROXY") == "1":
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-co"

TIME_ZONE = "America/Bogota"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    # El almacenamiento con manifiesto (hash en el nombre del archivo, para
    # que el navegador cachee mejor) requiere haber corrido collectstatic;
    # en desarrollo y pruebas se usa el almacenamiento simple de WhiteNoise.
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else "whitenoise.storage.CompressedStaticFilesStorage"
        )
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Modelo de IA en la nube para la descripción asistida (clave en ANTHROPIC_API_KEY).
MAZUCA_MODELO_IA = os.environ.get("MAZUCA_MODELO_IA", "claude-opus-5")

# Gemini: el proveedor de IA en la nube que se usa activamente en RICORA
# (clave en GEMINI_API_KEY). Claude sigue disponible como alternativa desde
# el panel técnico, pero Gemini es el que se configura y prueba primero.
# gemini-2.5-pro dejó de estar disponible para claves nuevas (Google responde
# 404); los modelos Pro tienen cuota 0 en el plan gratuito. Comprobado con la clave real.
MAZUCA_MODELO_IA_GEMINI = os.environ.get("MAZUCA_MODELO_IA_GEMINI", "gemini-3.5-flash")

# F16: un único punto de ingreso para los dos perfiles (archivista y
# invitado de consulta) — /admin/login/ exige is_staff y rechaza a un
# invitado de consulta de plano, así que no puede ser el LOGIN_URL general.
LOGIN_URL = "ric_login"
LOGIN_REDIRECT_URL = "panel"

# M11: invitación por correo al crear una cuenta. Sin EMAIL_HOST configurado
# el sistema lo dice claramente en vez de fingir que envió algo.
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "1") == "1"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "ricora@localhost")

# M1 (RF-M1-03): tamaño máximo de un archivo cargado.
RICORA_TAMANO_MAXIMO_MB = int(os.environ.get("RICORA_TAMANO_MAXIMO_MB", "200"))
# Archivos pesados: por encima de 2,5 MB Django escribe la carga a un archivo
# temporal en disco en vez de tenerla en memoria; la huella se calcula por
# bloques. Solo el cuerpo que NO es archivo tiene el límite de memoria.
FILE_UPLOAD_MAX_MEMORY_SIZE = 2_621_440
