# Generated by Django 5.2.17 on 2026-09-24 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("acervo", "0003_documento_publicado_documento_texto_publico_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RevisionDatosPersonales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("detector_version", models.CharField(max_length=20)),
                (
                    "hash_texto",
                    models.CharField(
                        help_text="Huella del texto revisado; si el texto cambia, hay que revisar de nuevo.",
                        max_length=64,
                    ),
                ),
                ("hallazgos", models.JSONField(default=list)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de decisión"),
                            ("publicable", "Publicable sin cambios"),
                            ("anonimizar", "Publicable con datos ocultos"),
                            ("restringido", "Acceso restringido"),
                        ],
                        default="pendiente",
                        max_length=12,
                    ),
                ),
                ("motivo", models.TextField(blank=True)),
                ("fecha_decision", models.DateTimeField(blank=True, null=True)),
                (
                    "decidido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisiones_datos",
                        to="acervo.documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "revisión de datos personales",
                "verbose_name_plural": "revisiones de datos personales",
                "ordering": ["-id"],
            },
        ),
    ]
