# Generated by Django 5.2.17 on 2026-09-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Criterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                (
                    "proceso",
                    models.CharField(
                        choices=[
                            ("clasificacion", "Clasificación"),
                            ("descripcion", "Descripción"),
                            ("valoracion", "Valoración"),
                            ("metadatos", "Gestión de metadatos"),
                            ("acceso", "Acceso"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "atributo",
                    models.CharField(
                        choices=[
                            ("autenticidad", "Autenticidad"),
                            ("integridad", "Integridad"),
                            ("accesibilidad", "Accesibilidad"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "enunciado",
                    models.TextField(
                        help_text="Lo que debe cumplir la solución de IA."
                    ),
                ),
                (
                    "verificacion",
                    models.TextField(
                        help_text="Cómo comprueba la entidad que el criterio se cumple."
                    ),
                ),
                ("fuente_normativa", models.CharField(max_length=255)),
                ("obligatorio", models.BooleanField(default=True)),
                (
                    "riesgo_asociado",
                    models.CharField(
                        blank=True,
                        help_text="Sesgo, pérdida de contexto, trazabilidad…",
                        max_length=255,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador (pendiente de Fase 4)"),
                            ("validado", "Validado en la tesis"),
                        ],
                        default="borrador",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["proceso", "codigo"],
            },
        ),
    ]
